# Generated by Django 2.2.2 on 2019-07-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='id_generator',
        ),
    ]
