# Generated by Django 2.2.2 on 2019-09-03 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_id_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 10, 24, 14, 93518), verbose_name=datetime.datetime(2019, 9, 3, 10, 22, 58, 227894)),
            preserve_default=False,
        ),
    ]
