# Generated by Django 2.2.2 on 2019-09-03 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20190903_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 10, 25, 54, 875320)),
        ),
    ]
