# Generated by Django 2.2.2 on 2019-09-03 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_auto_20190903_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='swear_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='id',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 11, 37, 27, 587754)),
        ),
    ]
